src/plugins/autolink.js
Hi @ipeychev , 
I think here we don't need extra tests, as they are already covered. I just changed from where we get the editor, so no behaviour has been modified.
=> Get current "editor" from the event.

src/ui/react/src/oop/attribute.js, src/ui/react/test/attribute.js
Fixes #294
Before this patch, the default value of a `writeOnce` attribute could not be overriden with a config value. The tests were expecting such behaviour.
=> Make sure a config value can override the default value of a writeOnce attribute

src/ui/react/src/adapter/alloy-editor.js, src/ui/react/test/alloy-editor.js
Fixes #290 
Note: testing that requires quite some changes in the alloy-editor tests but I'm unsure if the test structure in this patch is the best one.
=> Allow to prevent AlloyEditor from setting contenteditable to true on its srcNode

src/ui/react/src/components/main.jsx, src/ui/react/test/alloy-editor.js
Hey @ipeychev, what do you think about this? Do you think firing on `componentDidUpdate` could cause some performance impact? Should we have an attribute to control wether we fire the event or not?
In addition... I think it's time we get some event emitter in there so we can start firing events from the AlloyEditor instance instead of CKEditor. What do you think?
=> Fire editorUpdate event when UI state is updated

src/ui/react/src/adapter/alloy-editor.js, src/ui/react/src/components/main.jsx
Hey @ipeychev, this is the fix for #371.
I've been fighting to get a proper test for a while and I can't spend much more time on it. On one side, `React.TestUtils` can't simulate pure DOM events, so we have to use CKEditor jquery or add something else.
Also, for some reason, I was observing a weird initialization order when destroying and recreating an AlloyEditor instance, which prevented me from covering the use case where we destroy and recreate the editor.
=> Use focus event instead of contentDOM to make sure initialization always runs

src/plugins/dragresize.js, src/plugins/tableresize.js, src/plugins/tabletools.js
Hey @ipeychev this fixes #379.
I tested this using a custom build of CKEditor with all of the default plugins. To be able to create proper tests, we'd have to commit that one and use it as part of the test process, so we'd have to keep two copies of CKEditor in our repo. 
Do you think it is worth keeping it for this, or future testing purposes?
=> Do not prevent plugin from being created if original CKEditor one exists

src/ui/react/src/components/base/button-keystroke.js, src/ui/react/src/components/buttons/button-bold.jsx, src/ui/react/src/components/buttons/button-italic.jsx, src/ui/react/src/components/buttons/button-link.jsx, src/ui/react/src/components/buttons/button-underline.jsx, src/ui/react/test/button-bold.jsx, src/ui/react/test/button-code.jsx, src/ui/react/test/button-h1.jsx, src/ui/react/test/button-h2.jsx, src/ui/react/test/button-italic.jsx, src/ui/react/test/button-link.jsx, src/ui/react/test/button-ol.jsx, src/ui/react/test/button-quote.jsx, src/ui/react/test/button-strike.jsx, src/ui/react/test/button-subscript.jsx, src/ui/react/test/button-superscript.jsx, src/ui/react/test/button-ul.jsx, src/ui/react/test/button-underline.jsx
Hey @ipeychev, this adds the requested feature in #417. As a bonus, I've applied the mixin to the `bold`, `italic` and `underline` buttons to fix #141.
I'm from home now, so I've only been able to verify that the tests pass on Chrome and Firefox...
What do you think?
=> ButtonKeystroke (#417, #141)

src/ui/react/src/components/base/button-style.js, src/ui/react/src/components/buttons/button-bold.jsx, src/ui/react/src/components/buttons/button-italic.jsx, src/ui/react/src/components/buttons/button-strike.jsx, src/ui/react/src/components/buttons/button-subscript.jsx, src/ui/react/src/components/buttons/button-superscript.jsx, src/ui/react/src/components/buttons/button-underline.jsx
Hey @ipeychev, this is the improvement we discussed for https://github.com/liferay/alloy-editor/issues/533.
Now, this will work out of the box:
```javascript
[...]
AlloyEditor.editable('editable', {
coreStyles_bold: customBoldStyle,
coreStyles_italic: customItalicStyle,
coreStyles_underline: customUnderlineStyle,
coreStyles_strike: customStrikeStyle,
coreStyles_subscript: customSubscriptStyle,
coreStyles_superscript: customSuperscriptStyle
});
```
=> Support style string definition (Fixes #533)

src/ui/react/src/adapter/alloy-editor.js, src/ui/react/test/alloy-editor.js
Hey Iliyan!
@antoniopol06 added here tests for the `readOnly` feature. While doing so, he also uncovered a bug when the editor was being initialized with `readOnly` to true, so yay! ☺️
=> ReadOnly feature tests (#538)

src/ui/react/src/adapter/alloy-editor.js, src/ui/react/src/adapter/main.js
This is a potential fix for #724. The code path is not yet tested because we didn't find a proper way to test the `LoadLanguageResources` path, if I remember correctly.
=> Sets editor property before potentially start the render phase

src/ui/react/src/adapter/alloy-editor.js, src/ui/react/test/alloy-editor.js
Hey @ipeychev, I've rebased and fixed the conflicts. Turns out the test file was conflicting with some previously added ones... I think it's the first time we run into problems by writing too many tests 😂
=> Updates test message and adds default case

src/core/link.js, test/core/test/link.js
=> Adding on page bookmark support to links

package.json, src/ui/react/gulp-tasks/test.js, src/ui/react/karma-saucelabs.js, src/ui/react/karma-soucelabs.js
To provide two distinct testing process one which uses local browser instances and another that attempts to establish a connection with SauceLabs and use the specified VMs.
Created two gulp separate tasks:
- `gulp test` (local)
- `gulp test:saucelabs` (CI)
=> Adds karma-saucelabs and fixes typo

README.md, src/plugins/addimages.js
A customer noted to us that users are unable to drag and drop text or images internally in AlloyEditor. I verified that this is not only the case in the portal but on alloyeditor.com as well.
You cannot internally drag and drop text or images within AlloyEditor.
*Steps to Reproduce :*
1. Content -> Blogs -> Add Blog Entry
2. Upload an image to the blog post content
3. Write text to the body content
4. Attempt to drag image in between some words
Expected Results: The image is moved to the location the cursor indicates.
Actual Results: The cursor properly traces where you will 'drop' the image but on mouse up nothing happens.  The image is not moved.
I made it so the preventDefault is only fired by AlloyEditor's dragdrop function when we need to specifically override the behavior, otherwise …
=> Drag and Drop Doesn't Work Within the Editor Fixes #839

src/ui/react/src/components/main.jsx
https://github.com/liferay/alloy-editor/issues/852
In [_setUIHidden](https://github.com/liferay/alloy-editor/blob/d34fe1b67b9a70e417aac72842ead20222131903/src/ui/react/src/components/main.jsx#L347) we check whether the user's interaction target is within the editor / editable area.  
The issue is that dragresize dynamically generates the drag handles outside of the editable div and making `editable.contains(targetNode)` false and thus we're treating resizing as though we're outside the UI.
We modify the [_setUIHidden check](https://github.com/liferay/alloy-editor/blob/d34fe1b67b9a70e417aac72842ead20222131903/src/ui/react/src/components/main.jsx#L359) to also test whether we're resizing an image.  We do this by checking whether the target is within the div with id "ckimgrsz".
Chrome and …
=> Resize visible

src/ui/react/src/selections/selection-test.js
https://github.com/liferay/alloy-editor/issues/848
For most browsers "check if selection is empty" is sufficient to resolve this issue.
However the Chrome react unmount issue is different as CKEditor injects [7 zero-width space characters].  We test whether the selection is an image in linkSelectionTest to handle this.
Chrome, IE 11, and FireFox.
gif of issue and fix on Chrome
https://imgur.com/a/h08XgJt
=> Image link dev

src/ui/react/src/components/base/widget-position.js
The toolbar may overflow on the right side of the screen if the user has a smaller screen or resizes the browser. This will prevent users from seeing toolbar options.
Example of issue can be found here: https://github.com/liferay/alloy-editor/issues/866#issuecomment-404677783
By checking if the placement of the `left` is going to be greater than the document's body offset subtracted by the toolbar width, we can prevent any overflow.
=> Adjust toolbar placement on right side to prevent overflow

src/plugins/autolink.js
The issue was introduce by the following commit:
"Adds a way to correct paste behavior of an URL"
32040b8
Pasting text from the clipboard which contains url(s) the first url is automatically moving to the beginning of the paragraph replacing with an anchor link. The other urls stay untached.
The issue is only reproducable when copying text from the clipboard
which has url(s)
and not contains new lines
and the text is not copied from the editor itself.
When typeing text in the editor the url(s) are replacing with anchor links correctly.
The original solution was wrong: only replaced the first url in the text and placed the anchor link to the beginning of the text.
I changed the REGEX_URL to find all the url occurrence in the text and i rewrited the paste function to replace all the urls in …
=> Fixes #885 | Fix editor.on paste function and enhance REGEX_URL

src/plugins/dragresize_ie11.js
**Issue**
#911
In IE11 when changing the image's alignment to the right the drag resize handle moves from it's expected lower righthand location to the lower lefthand side. However, the handle is misplaced slightly to the right of the lefthand corner.
**Solution**
The CSS property **left** for cke_image_resizer_left just has to be adjusted to be -25px isntead of -5px.
The issue only appears in IE11 and have tested also in Chrome, Firefox, and Edge. The issue is only reproducible on Liferay AlloyEditor.
Let me know if there are any questions or comments.
Thank you.
=> Fixes #911 Use correct CSS to place drag resize handle at the corner

src/plugins/autolink.js
Resent PR https://github.com/liferay/alloy-editor/pull/909
Fixed typo that prevented the fix from working correctly.
> ## Issue
> https://github.com/liferay/alloy-editor/issues/908
> When copying and pasting a link in IE11, the pasted link will contain additional tags `<u><font>`.
> 
> ## Solution
> I created a check that will search for these unwanted tags. In this issue, the `<u><font color="` tag will be present and will be used to identify this issue. I did not include the color since this issue may occur with different colors. If they are found, they will be replaced with an empty space making sure to remove the start and end tags. It will search through the whole string so it will remove multiple tags.
> 
> The issue only appears in IE11 and have tested also in Chrome, Firefox, and …
=> Fixes #908 Remove unwanted tags after paste

src/plugins/dragresize_ie11.js
Currently, IE11 only has one resize handle when resizing an image within AlloyEditor while other browsers (Chrome, Firefox) have four.  The task at hand is to implement resizing for IE11 such that it has a total of four drag handles and behaves in the same way as other browsers.
https://github.com/liferay/alloy-editor/issues/924
- Add styling for the four drag handles on the image resizer (one drag handle on each corner).  
- Add four drag handles as child elements of the image resizer, each with its proper CSS style
- `factorX` and `factorY` can be either +1 or -1, and they take into account which drag handle is being used.
- Height and width adjustment with `adjustToX()` and `adjustToY()` methods use `factorX` and `factorY` to determine whether to enlarge or shrink an image.
- No longer …
=> Fixes #924 Add four drag handles for image resizing

package-lock.json, package.json
Resolves a subset of the security issues identified by `npm audit`.
Before:
found 27 vulnerabilities (16 low, 1 moderate, 9 high, 1 critical)
(full audit: https://gist.github.com/wincent/96a0bae65e9a5b681c3103bb6a9c5471)
After:
found 15 vulnerabilities (7 low, 1 moderate, 6 high, 1 critical)
(full audit: https://gist.github.com/wincent/c61df833b3855ea5efa1ae108e7c5006)
`npm run test` is clean after the update:
```
15 01 2019 14:06:26.772:INFO [karma]: Karma v1.4.0 server started at http://0.0.0.0:9876/
15 01 2019 14:06:26.773:INFO [launcher]: Launching browser Chrome with unlimited concurrency
15 01 2019 14:06:26.791:INFO [launcher]: Starting browser Chrome
15 01 2019 14:06:27.799:INFO [Chrome 71.0.3578 (Mac OS X 10.13.6)]: Connected on socket c-wYPd2u1z3iqI36AAAA with id 39092991
Chrome …
```
=> Update Karma dependency to resolve security issues

karma.js, package-lock.json, package.json, src/components/uibridge/button.jsx, src/components/uibridge/menu-button.jsx, src/components/uibridge/panel-menu-button.jsx, src/components/uibridge/richcombo.jsx
For: https://issues.liferay.com/browse/IFI-409
This PR ports us away from the four places where we're using `createReactClass`.
=> Migrate away from reactCreateClass

package-lock.json, package.json, scripts/build/gulp/tasks/fonts.js
Added in aa2f8f76b25262982253e3e8a394c7ffdb1284ae and looks like it was
never used, not even in that commit.
Splitting this off from #958 to see if a smaller commit passes Travis.
=> Remove never-used gulp-empty dependency

scripts/build/gulp/tasks/build.js, scripts/build/gulp/tasks/css.js
As described in the commit messages, this PR just applies a little clean-up noted while doing some initial investigation for IFI-406.
=> Apply some minor clean-up while investigating slow build speeds

package.json, scripts/build/gulp/tasks/build.js, webpack.common.js, webpack.dev.js
This is just an intermediate step towards making builds faster.
Before this PR, our build process looked like this:
1. Run "build:assets" using the `gulp` executable.
2. Do webpack.prod build using the `webpack` executable.
3. Do webpack.dev build using the `webpack` executable.
These serial processes took about 2s, 12s, and 38s respectively on my machine: a total of about 52s.
After this commit, we do this:
1. Use `gulp` to do everything the "build:assets" task did.
2. In parallel, run the two webpack builds from the same `gulp` invocation.
In the end, we wind shave only a few seconds from the original runtime (ie. going down to just under 50s) because we're always going to be limited by the length of the slowest job, and that job will actually run a little slower than usual when in …
=> Parallelize webpack builds

package-lock.json, package.json, webpack.prod.js
In summary:
- Latest webpack minor version.
- Uglify → Terser
- Drop low-impact optimizations.
- Turn on caching.
- Turn on parallel minification.
=> Speed up build with improvements to the minification configuration

karma-saucelabs.js, package-lock.json, package.json
Before:
found 10 vulnerabilities (4 low, 5 high, 1 critical) in 17824 scanned packages
After:
found 8 vulnerabilities (3 low, 4 high, 1 critical) in 17615 scanned packages
`npm run dev && npm run test` still green after this change is applied.
Note that I had to change one of the Sauce Labs config settings in order to get this to pass in Travis; without this change, CI runs were blowing up with:
```
ERROR [SaucelabsLauncher]: Error: Error: no ssl bump domains(s) not
valid, invalid domain(s): -B all
```
=> Update karma-sauce-launcher as recommended by `npm audit`

package-lock.json, package.json
Before:
found 8 vulnerabilities (3 low, 4 high, 1 critical) in 17615 scanned packages
After:
found 6 vulnerabilities (2 low, 4 high) in 17609 scanned packages
`npm run dev && npm run test` still green after this change.
Originally tried in #958, #965, #967, #972. Fifth time lucky, as they say!
=> Update mocha as recommended by `npm audit`

package-lock.json, package.json, scripts/build/gulp/gulpfile.js
This dependency doesn't do much for us: removing it shows that we can get by without it (note how we used four lines invoking the package before this commit, and when we remove the package we can get an equivalent outcome with four lines, leaving the total count unchanged).
In any case, the real motivation here is that when we move to Gulp v4 (see #980), the pattern is to refer to tasks using function references rather than strings, which means we'd have to manually import the "build" tasks additionally anyway. Reducing our dependency footprint is just a bonus.
Test plan: `npm run build` and see that everything still works.
=> Remove require-dir dependency

package.json, webpack.prod.js
Add a "prepublishOnly" task that errors out if we try to publish code that isn't formatted with Prettier. Also runs the tests for obvious reasons.
Once we have linting back up and running we can fail even faster with respect to formatting and warn or error at lint-time.
This commit includes a fix for one incorrectly formatted file. There are also a couple of others that need re-formatting:
- scripts/build/gulp/tasks/build.js
- scripts/build/gulp/tasks/css.js
but I am leaving those so as to avoid an unnecessary conflict with #982.
=> Fixes #983 - Make sure code is correctly formatted before publishing

.travis.yml
We were pegged at 8, but let's see if we have any more stability by
using the latest stable release at all times:
https://docs.travis-ci.com/user/languages/javascript-with-nodejs/#specifying-nodejs-versions
=> Use a more recent Node in Travis

.editorconfig
This one is deemed obsolete thanks to Prettier.
Closes: https://github.com/liferay/alloy-editor/issues/988
=> Fixes #988 - Remove .editorconfig

src/components/toolbars/toolbar-add.jsx
Before the fix:
After the fix:
=> Fixes #992 - Left-side add icon not showing up on 2.x branch #992

.eslintrc.js, src/plugins/Resizer.es.js
```
19:24  error  'box' is defined but never used    no-unused-vars
71:38  error  'index' is defined but never used  no-unused-vars
```
I just removed the `index` param from the `forEach` call because it is totally standard to omit it.
For the `box` param, I added configuration to mark params starting with `_` as unused, because all the neighboring methods take a `box` and use it, and I wanted this one to basically say, "I know all my neighbors take a `box` and I could use it too but I don't need to".
Related: #990
=> Fix lints in plugins/Resizer.es.js

package-lock.json, package.json, scripts/build/gulp/tasks/build.js, webpack.common.js
According to https://webpack.js.org/guides/build-performance/ accessing fields on the stats object can be expensive. So, I changed things here to only access it if `stats.hasErrors()` is true, or if you pass in an environment variable:
```sh
env STATS=1 npm run build
```
By default, stats won't be shown. Instead, you'll see this in the build output:
```
[15:30:44] Starting 'build:webpack.dev'...
Not showing webpack stats; run with `env STATS=1` to show
[15:31:07] Finished 'build:webpack.dev' after 23 s
Not showing webpack stats; run with `env STATS=1` to show
[15:31:11] Finished 'build:webpack.prod' after 27 s
```
In testing this, I found a bug in the original code which explains why the stats output is not in color. I was calling `stats.stats.toString({colors: true})` but I needed to …
=> Fixes #1000 - Speed up builds

src/adapter/main.js
Fixes:
```
202:4  error  Unexpected 'this'  babel/no-invalid-this
```
Not sure which recent change caused the rule name to change here, but I
didn't notice the breakage in the flood of lints that we currently
still have (157 errors on current `HEAD`).
=> Restore lint suppression in src/adapter/main.js

src/components/buttons/button-embed-edit.jsx
Linter was complaining:
```
src/components/buttons/button-embed-edit.jsx
147:6  error  HTML entities must be escaped  react/no-unescaped-entities
```
Looks like a bug introduced in 88ec95553. I love it when the linter finds (non-stylistic) issues!
=> Remove stray ">" from button-embed-edit.jsx, fixing 1 lint

src/components/buttons/button-commands-list.jsx
Fixes:
```
src/components/buttons/button-commands-list.jsx
54:3  error  Do not use findDOMNode  react/no-find-dom-node
```
Test plan: Did the usual `npm run dev && npm run test && npm run start`, but I don't know if this component gets rendered in the demo. (Any tips on how to verify this @julien?)
Related:
- https://github.com/liferay/alloy-editor/issues/990
- https://github.com/liferay/alloy-editor/issues/1010
=> Fix lint in button-commands-list.jsx (react/no-find-dom-node)

src/core/link.js, src/plugins/autolink.js, src/plugins/dragresize_ie.js, src/plugins/dragresize_ie11.js
```
src/core/link.js
5:49  error  Unnecessary escape character: \.  no-useless-escape
6:49  error  Unnecessary escape character: \:  no-useless-escape
src/plugins/autolink.js
81:26  error  Unnecessary escape character: \"  no-useless-escape
81:34  error  Unnecessary escape character: \"  no-useless-escape
src/plugins/dragresize_ie.js
29:30  error  Unnecessary escape character: \%  no-useless-escape
src/plugins/dragresize_ie11.js
22:30  error  Unnecessary escape character: \%  no-useless-escape
```
=> Fix 6 no-useless-escape lints

src/components/buttons/button-link-autocomplete-list.jsx
```
src/components/buttons/button-link-autocomplete-list.jsx
175:9  error  'instance' is assigned a value but never used  no-unused-vars
```
The `instance` variable was originally added in bdbd6b03d, but it is not needed after 2dc8faf99.
=> Fix 1 lint in button-link-autocomplete-list.jsx (no-unused-vars)

src/components/buttons/button-paragraph-align.jsx
Fixes:
```
src/components/buttons/button-paragraph-align.jsx
22:9  error  'activeAlignment' is assigned a value but never used  no-unused-vars
```
Added in 1ab02307b380, I believe, and never used.
=> Fix 1 lint in button-paragraph-align.jsx (no-unused-vars)

src/components/buttons/button-separator.jsx
```
src/components/buttons/button-separator.jsx
6:26  error  'props' is defined but never used. Allowed unused args must match /^_/  no-unused-vars
```
=> Fix lint in button-separator.jsx (no-unused-vars)

src/components/uibridge/button.jsx, src/components/uibridge/menu-button.jsx, src/components/uibridge/richcombo.jsx
When I last touched these files I kept these variables in there as a kind of documentation, but I don't think they provide much value to be honest. Removing them to pacify these lints:
```
src/components/uibridge/button.jsx
14:6  error  'UNSUPPORTED_BUTTON_API' is assigned a value but never used  no-unused-vars
src/components/uibridge/menu-button.jsx
15:6  error  'UNSUPPORTED_MENUBUTTON_API' is assigned a value but never used  no-unused-vars
src/components/uibridge/richcombo.jsx
15:6  error  'UNSUPPORTED_RICHCOMBO_API' is assigned a value but never used  no-unused-vars
```
With this change, those three files are lint-clean.
=> Fix 3 lints by removing UNSUPPORTED_*_API variables

src/components/uibridge/uibridge.js
```
src/components/uibridge/uibridge.js
28:33  error  Use the rest parameters instead of 'arguments'  prefer-rest-params
```
I don't know why the initial implementation did this, perhaps to be future-proof in case the upstream "add" function ever takes more than 3 parameters (most likely just to avoid spelling out the parameters explicitly). To remain future proof I could have changed it to:
```
editor.ui.add = function(name, type, definition, ...rest) {
originalUIAddFn.call(this, name, type, definition, ...rest);
```
However, it seems like overkill because I think it's pretty unlikely that the signature will change from what is currently documented:
https://ckeditor.com/docs/ckeditor4/latest/api/CKEDITOR_ui.html
=> Fix 1 lint in uibridge/uibridge.js (prefer-rest-params)

src/components/uibridge/menu.jsx
Wrote some old-school code to fix this:
```
src/components/uibridge/menu.jsx
79:5  error  The body of a for-in should be wrapped in an if statement to filter unwanted properties from the prototype  guard-for-in
```
FWIW, the "clever" way to do this with `Object.entries().forEach()` ends up being less readable because of the need to use a non-arrow function and pass in `this`.
Usual tests: `npm run dev && npm run test && npm run start` and look at demo.
=> Fix lint in uibridge/menu.jsx (guard-for-in)

src/plugins/dragresize.js, src/plugins/dragresize_ie.js, src/plugins/dragresize_ie11.js
```
src/plugins/dragresize_ie.js
330:6   error  The body of a for-in should be wrapped in an if statement to filter unwanted properties from the prototype  guard-for-in
554:4   error  The body of a for-in should be wrapped in an if statement to filter unwanted properties from the prototype  guard-for-in
src/plugins/dragresize_ie11.js
143:4   error  The body of a for-in should be wrapped in an if statement to filter unwanted properties from the prototype  guard-for-in
384:6   error  The body of a for-in should be wrapped in an if statement to filter unwanted properties from the prototype  guard-for-in
1038:4   error  The body of a for-in should be wrapped in an if statement to filter unwanted properties from the prototype  guard-for-in
src/plugins/dragresize.js
238:4   error  The body of a …
```
=> Fix 9 remaining "guard-for-in" lints

src/core/uicore.js
```
src/core/uicore.js
99:54  error  'event' is defined but never used. Allowed unused args must match /^_/  no-unused-vars
135:5   error  Unexpected var, use let or const instead                                no-var
154:34  error  'event' is defined but never used. Allowed unused args must match /^_/  no-unused-vars
```
Usual tests: `npm run dev && npm run test && npm run start` and check in demo that things work and no errors in console.
=> Fix 3 lints in src/core/uicore.js

src/core/debounce.js
```
src/core/debounce.js
25:34  error  Unexpected 'this'                               babel/no-invalid-this
36:18  error  Use the rest parameters instead of 'arguments'  prefer-rest-params
```
The use of `this` in this function is expected (required, even), so suppress that lint.
The use of `arguments`, however, isn't required, so I replaced it.
This function isn't like other debounce functions I've seen: it allows you to pass a set of default arguments at creation-time, and in the absence of arguments being passed at call-time you get the defaults. That sounds reasonable enough (although a more conventional way to do this would be to use `bind()`).
The weirder thing, though, is what happens if you supply defaults at creation-time *and* also pass arguments at call-time: in this case, the …
=> Fix 2 lints in core/debounce.js

src/oop/attribute.js
```
src/oop/attribute.js
112:13  error  Use the spread operator instead of '.apply()'  prefer-spread
```
Test plan: `npm run dev && npm run test && npm run start` then check out demo.
=> Fix lint in oop/attribute.js (prefer-spread)

src/oop/oop.js
This commit fixes the one lint in "oop/oop.js", which, BTW, is an awesome filename.
```
src/oop/oop.js
18:3  error  Expected an object to be thrown  no-throw-literal
```
Test plan: `npm run dev && npm run test`
=> Fix lint in src/oop/oop.js (no-throw-literal)

src/core/selection-region.js
```
src/core/selection-region.js
288:8  error  'rangeCount' is assigned a value but never used  no-unused-vars
```
The earliest trace of this that I can find is in e0ec699dceaa683b4 ("So far", authored in 2014), and it seems it was never used then or any time since.
Test plan: `npm run dev && npm run test && npm run start` and check demo.
=> Fix lint in core/selection-region.js (no-unused-vars)

src/components/buttons/button-link-browse.jsx
```
src/components/buttons/button-link-browse.jsx
75:31  error  'LinkBrowse' is not defined  no-undef
```
This one looks to be another legit bug. Yay for the linter!
Test plan: `npm run dev && npm run test && npm run start`, see demo.
=> Fix bad variable name in button-link-browse.jsx (no-undef)

src/components/buttons/button-embed-video-edit.jsx
```
src/components/buttons/button-embed-video-edit.jsx
99:5   error  'videoUrl' is not defined                              no-undef
```
Also looks like a legit bug.
Test plan: `npm run dev && npm run test && npm run start` and hit demo.
=> Fix bad identifier in button-embed-video-edit.jsx (no-undef)

src/plugins/dragresize_ie11.js
```
src/plugins/dragresize_ie.js
1410:5   error  'moveRatio' is not defined           no-undef
```
This is another "no-undef" "bug" but not like the ones in #1025 and #1026. Here we have something that is missing a `let` keyword, but it turns out variable is unused anyway, so I just removed it.
Last use was removed in d6145d2c4ad866fbe, I believe.
In any case, no real harm here at runtime, because I believe it just ended up assigning to `window.moveRatio`.
Test plan: `npm run dev && npm run test && npm run start`
=> Fix no-undef lint in src/plugins/dragresize_ie11.js

src/core/plugins.js, src/plugins/.eslintrc.js
This drops us from:
✖ 112 problems (112 errors, 0 warnings)
to:
✖ 80 problems (80 errors, 0 warnings)
on the current `HEAD`.
We're doing this because the plug-in system relies on this pattern pervasively (functions being invoked with a `this` value set from the outside). But we'd like to consider moving away from this pattern in the future, so we turn the errors into warning rather than suppressing them entirely.
I'm doing this with a cascading configuration file at "src/plugins/.eslintrc.js" that takes effect for the whole directory, plus a couple of disabling comments in one plug-in related place outside it. There are still a small number of "babel/no-invalid-this" violations outside the files that are affected by this commit, but they need to be looked at separately to determine what …
=> Turn "babel/no-invalid-this" into a warning in plug-in files

src/components/main.jsx, src/components/toolbars/toolbar-add.jsx, src/components/toolbars/toolbar-styles.jsx, src/core/table.js, src/plugins/dragresize.js, src/plugins/dragresize_ie11.js, src/plugins/embedurl.js
Fixes:
```
src/components/main.jsx
50:4   error  'event' is defined but never used. Allowed unused args must match /^_/  no-unused-vars
228:21  error  'event' is defined but never used. Allowed unused args must match /^_/  no-unused-vars
src/components/toolbars/toolbar-add.jsx
54:21  error  'prevProps' is defined but never used. Allowed unused args must match /^_/  no-unused-vars
54:32  error  'prevState' is defined but never used. Allowed unused args must match /^_/  no-unused-vars
src/components/toolbars/toolbar-styles.jsx
51:21  error  'prevProps' is defined but never used. Allowed unused args must match /^_/  no-unused-vars
51:32  error  'prevState' is defined but never used. Allowed unused args must match /^_/  no-unused-vars
src/core/table.js
384:20  error  'editor' is defined but …
```
=> Deal with 12 remaining "no-used-vars" lints related to function args

src/components/buttons/button-embed-video-edit.jsx, src/plugins/dragresize_ie11.js, src/plugins/tableresize.js, src/plugins/tabletools.js, test/plugins/test/autolink.js, test/ui/test/button-bridge.jsx
Fixes:
```
src/components/buttons/button-embed-video-edit.jsx
120:9   error  'icon' is assigned a value but never used              no-unused-vars
src/plugins/dragresize_ie11.js
95:8   error  'config' is assigned a value but never used                                                                 no-unused-vars
1045:4   error  The body of a for-in should be wrapped in an if statement to filter unwanted properties from the prototype  guard-for-in
1047:10  error  'dimension' is assigned a value but never used                                                              no-unused-vars
1050:9   error  'dimension' is not defined                                                                                  no-undef
1050:22  error  'dimension' is not defined …
```
=> Fix 8 more lints, including last of the "no-unused-vars"

src/components/buttons/button-accessibility-image-alt.jsx
We had this console spew:
```
react-dom.development.js:506 Warning: `value` prop on `input` should
not be null. Consider using an empty string to clear the component or
`undefined` for uncontrolled components.
```
With this change, we no longer pass a null-ish value as and the console is clean.
Test plan: `npm run dev && npm run test && npm run start`; then in demo, click on image, click on alt button, see console is clean and setting an alt still works.
Closes: https://github.com/liferay/alloy-editor/issues/1030
Internal: https://issues.liferay.com/browse/IFI-435
=> Eliminate React warnings when editing image alt attribute

src/core/tools.js
```
src/core/tools.js
92:15  error  Use the rest parameters instead of 'arguments'  prefer-rest-params
```
Test plan: `npm run dev && npm run test && npm run start`
=> Fix last lint in src/core/tools.js (prefer-rest-params)

src/plugins/dragresize.js
```
src/plugins/dragresize.js
541:18  error  Use the rest parameters instead of 'arguments'  prefer-rest-params
```
Test plan: `npm run dev && npm run build && npm run start`, check demo.
=> Fix last lint in src/plugins/dragresize.js (prefer-rest-params)

src/plugins/tabletools.js
```
src/plugins/tabletools.js
53:5  error  Unexpected var, use let or const instead   no-var
167:4  error  Unexpected var, use let or const instead   no-var
196:4  error  Unexpected var, use let or const instead   no-var
212:9  error  Unexpected var, use let or const instead   no-var
320:8  error  Unexpected var, use let or const instead   no-var
329:4  error  Unexpected var, use let or const instead   no-var
370:8  error  Unexpected var, use let or const instead   no-var
371:9  error  Unexpected var, use let or const instead   no-var
591:8  error  Unexpected var, use let or const instead   no-var
709:4  error  Unexpected var, use let or const instead   no-var
803:8  error  'lang' is assigned a value but never used  no-unused-vars
```
`lang` is safe to remove because the last references …
=> Fix 11 lints in src/plugins/tabletools.js

src/plugins/dragresize_ie11.js
```
src/plugins/dragresize_ie11.js
1239:7   error  Identifier 'resizer_ne' is not in camel case                                                                camelcase
1241:7   error  Identifier 'resizer_nw' is not in camel case                                                                camelcase
1243:7   error  Identifier 'resizer_se' is not in camel case                                                                camelcase
1245:7   error  Identifier 'resizer_sw' is not in camel case                                                                camelcase
```
Test plan: `npm run dev && npm run test`
=> Fix last 4 lints in dragresize_ie11.js

package.json
npm run lint:changed
And if you want it to be errors only, not warnings:
npm run lint:changed -- --quiet
And if you want it to run on added-but-not-yet-staged files, record the intent to add in the index first:
git add -N src/the-new-file.js
=> Add support for running lints on changed files only

src/plugins/tableresize.js
```
src/plugins/tableresize.js
98:4  error  Unexpected var, use let or const instead  no-var
99:4  error  Unexpected var, use let or const instead  no-var
100:4  error  Unexpected var, use let or const instead  no-var
275:5  error  Unexpected var, use let or const instead  no-var
377:3  error  Unexpected var, use let or const instead  no-var
412:3  error  Unexpected var, use let or const instead  no-var
```
Test plan: `npm run dev && npm run test && npm run start` and test table
functionality in demo.
=> Fix 6 lints in src/plugins/tableresize.js (no-var)

src/plugins/dragresize_ie.js
```
src/plugins/dragresize_ie.js
862:8  error  'moveRatio' is assigned a value but never used  no-unused-vars
```
This is the exact same issue as fixed in "dragresize_ie11.js" in
39d4d18b1ff2e4d. With hundreds of lint errors in the report, I didn't
see this file had the same thing.
Fix is same: variable is unused, so removed it.
Test plan: `npm run dev && npm run test`
=> Fix last lint in dragresize_ie.js (no-unused-vars)

scripts/build/gulp/tasks/build.js
Building on Windows is not officially supported, but we can easily remove one issue on that platform by removing our use of the `PWD` environment variable, which won't be set on Windows.
I can't remember why I did it this way, but I am guessing it was to avoid the ugliness of the "../../../..".
Test plan: add a `console.log` statement to sanity check the constructed path and do `npm run build`.
=> Don't use process.env.PWD in build

package.json
Same idea as #1041, this one allows you to run Prettier only on files you've touched.
In testing this I learned some things about Git globs.
- `'src/*.js'` is actually the same as `'src/**/*.js'`; it matches at   any level.
- There is a "magic" globbing identifier that you can use to use actual "**" syntax (eg. `'(:glob)src/**/*.ls'`) but if you use it with multiple pathspecs, only the first one will be used.
- `'*.js'` will match anywhere in the hierarchy.
So, to make this work only for .js files in the root, I can't use  a pathspec of "*.js", because it will match files I don't want to match (like files in "lib/", for example). Instead, I am using shell parameter expansion to handle the top-level files, and pathspecs for the rest. No `(:glob)` magic because I need multiple pathspecs.
In …
=> Add "npm run format:changed"

src/plugins/dragresize_ie.js, src/plugins/dragresize_ie11.js
#1057 
In IE11, resizing an image and aligning will result in the image going back to its default size. 
Update the size of the image and add the style to the image. This will keep the size of the image when aligning. 
Thank you.
IE11
=> Fixes #1057 Keep styles in the image for IE

src/components/buttons/button-item-selector-image.jsx, src/components/buttons/button-item-selector-video.jsx
Since 8a0aaf7, this is leading to this in the console on clicking the left-hand-side "+" button:
```
checkPropTypes.js:19 Warning: Failed prop type: The prop `imageTPL` is marked as required in `ButtonCommand`, but its value is `undefined`.
in ButtonCommand (created by WidgetArrowBox)
in WidgetArrowBox (created by WidgetExclusive)
in div (created by WidgetExclusive)
in WidgetExclusive;
```
The prop is not used in the component, so it doesn't seem to be required after all. I also looked in the Liferay Portal and see no other mentions of this property name, so I think it is safe to remove.
Test plan: `npm run dev && npm run test && npm run start` and hit the demo.
Closes: #1065
=> Fixes #1065 - Resolve console warnings about imageTPL prop

scripts/build/gulp/tasks/css.js
We moved to SVG icons from font-based ones in d1b061729f9ca4f9476059c, but we have continued to include the font-related CSS in our build, which leads to console spam like this when you do certain things:
```
GET http://localhost:9000/alloy-editor/assets/fonts/alloyeditor-ocean.woff net::ERR_ABORTED 404 (Not Found)
GET http://localhost:9000/alloy-editor/assets/fonts/alloyeditor-ocean.ttf net::ERR_ABORTED 404 (Not Found)
```
(For example, if you hit "+" in the LHS margin and then hit the "+" icon in the pop-up toolbar.)
We should be able to omit this safely. There are still some straggling references to `ae-icon-*` classes in the codebase (apart from the `ae-icon-svg-*` ones, which are legit), but removing these will be the subject of another pull.
Tested plan: `npm run build && npm run …
=> Don't ship font-related CSS any more

package-lock.json, package.json
Before, you'd see something like this on every `npm run test`:
```
(node:59483) DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead
```
After upgrading the "karma-webpack" dependency, the output is clean and the tests still pass. (Discovered the guilty code by running with `node --trace-deprecation node_modules/.bin/karma start karma.js`.)
Closes: https://github.com/liferay/alloy-editor/issues/1056
=> Fixes #1056 - Silence deprecation warnings emitted during test runs

src/core/debounce.js, test/core/test/debounce.js
Principally, this PR address #1052 by making our debounce tests use fake timers. This should make the tests more robust and avoid spurious failures. Along the way I addressed a number of other issues:
- Got rid of unnecessary IIFE and "use strict"
- Updated `var` to `const`, `function` to arrow function etc
- Address problem where we were not exporting the debounce function and therefore weren't explicity testing it (see 296522e).
=> Fixes #1052 - Use fake timers and clean up debounce tests

webpack.dev.js
We need the "publicPath" setting to make this work. With this change, `npm run start` prints this:
```
ℹ ｢wds｣: Project is running at http://localhost:9000/
ℹ ｢wds｣: webpack output is served from /alloy-editor
ℹ ｢wds｣: Content not from webpack is served from ./dist
```
Note the "served from /alloy-editor" bit. (Prior to this commit is instead said "served from /".) This allows the "alloy-editor/alloy-editor-all.js" script that our demo index.html references to be hot-reloaded.
Test plan: `npm run dev && npm run start`; hit demo and see it working, then add a `console.log`, see webpack recompile, and see the browser reload the module without any intervention (output appears in console).
Closes: https://github.com/liferay/alloy-editor/issues/1081
=> Fixes #1081 - Make dev environment hot-reloading work

src/components/buttons/button-accessibility-image-alt.jsx, src/components/buttons/button-embed-video-edit.jsx, src/components/buttons/button-item-selector-audio.jsx, src/components/buttons/button-item-selector-image.jsx, src/components/buttons/button-item-selector-video.jsx, src/components/buttons/button-link-edit-browse.jsx
Follow-ups to comments posted on #1055:
- Remove empty `propTypes` declarations.
- Update the three new buttons merged while that PR was in-flight.
=> Context follow ups

BREAKING_CHANGES.md
BREAKING_CHANGES.md is basically unmaintained (last updated in 2015), so remove it. I would have preferred to merge its contents into CHANGELOG.md, but in testing with `github_changelog_generator` I found that it overwrites any manual changes made to the document.
=> Remove BREAKING_CHANGES.md

src/adapter/core.js, src/assets/lang/en.json, src/commands/index.js, src/commands/remove-image.js, src/components/buttons/button-remove-image.jsx, src/components/buttons/index.js, src/selections/selections.js
The next part of the fix is to add a button to update
images.
=> Fixes #1048 | Add button to remove images

package-lock.json
```
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ High          │ Prototype Pollusion                                          │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ handlebars                                                   │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ karma-coverage [dev]                                         │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ karma-coverage > istanbul > handlebars                       │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://npmjs.com/advisories/755 …
```
=> Fix dev dependency security issue identified by `npm audit`

src/plugins/embed.js, src/plugins/priorities.js
The "embed" plugin checks to see whether pasted text matches a regex for strings starting with "http://" (or "https://"), but the "autolink" plug-in also listens to paste events and ends up transforming any links into anchor tags before the "embed" plug-in sees them. This means that the regex doesn't match and the embed will never work.
In this commit we add a priority mechanism in order to allow the "embed" plug-in to run first.
The gotcha: when we paste a link, the "selectionChange" handler runs in the "embed" plug-in and ends up firing an "editorInteraction" event with the new selection, and that means we see the link toolbar pop-up. Previously on pasting a link, no toolbar would appear. Still need to find a solution for that.
Test plan: `npm run dev && npm run test && npm run start`; …
=> Fix #1109 auto-embedding of pasted video (etc) URLs

src/plugins/dragresize_ie11.js, src/plugins/imagealignment.js
Resent from https://github.com/liferay/alloy-editor/pull/1098
> #1061
> https://issues.liferay.com/browse/LPS-90092
> 
> Removing the unnecessary alignment to both Chrome and IE will fix this issue. Removing the addition of center alignment to the parent in chrome, will allow the editor to function correctly in chrome. Also adding a check to add the center alignment to IE when it sees that the element contains marginLeft and marginRight auto.
> Let me know if there are any questions or comments about this.
> Thank you.
Let me know if there is anything that needs to be changed or added.
Thank you.
=> Fixes #1061 Allow only required style for IE and other browsers

.prettierignore
I failed to include this when I prepared #1107. If I had run `npm run format` I would have noticed.
Test plan: run `npm run format` and see no changes.
=> Update .prettierignore to be aware of new location of generated files

test/ui/test/button-bold.jsx, test/ui/test/button-code.jsx, test/ui/test/button-h1.jsx, test/ui/test/button-h2.jsx, test/ui/test/button-image-align-center.jsx, test/ui/test/button-image-align-left.jsx, test/ui/test/button-image-align-right.jsx, test/ui/test/button-italic.jsx, test/ui/test/button-ol.jsx, test/ui/test/button-paragraph-align-left.jsx, test/ui/test/button-paragraph-align-rigth.jsx, test/ui/test/button-paragraph-center.jsx, test/ui/test/button-paragraph-justify.jsx, test/ui/test/button-quote.jsx, test/ui/test/button-strike.jsx, test/ui/test/button-subscript.jsx, test/ui/test/button-superscript.jsx, test/ui/test/button-twitter.jsx, test/ui/test/button-ul.jsx, test/ui/test/button-underline.jsx
I broke some tests by removing Zepto in:
https://github.com/liferay/alloy-editor/pull/1087
Didn't notice though because many of our tests are silently failing; related issue that I'm currently working on for that:
https://github.com/liferay/alloy-editor/issues/1123
We can replace these Zepto usages with classList because it is available on all of our supported platforms:
https://caniuse.com/#feat=classlist
Test plan: run tests in browser with Karma config `singleRun: false` so that I can see the failures no longer appear in the console.
=> Fix tests broken by Zepto removal

karma.common.js
This one had me scratching my head for a while. While working on:
https://github.com/liferay/alloy-editor/issues/1123
I noticed that we weren't setting up the React context when rendering in tests, but when we did set it up, the context consumers still weren't getting the context.
Adding some logging, I could see that the context module was getting evaluated over and over again (123 times!), and I was able to confirm that we were getting a different (ie. `!==`) context object every time. Analysis in the debugger revealed that webpack was requiring modules by evaling their string representations, which meant that usual module once-only semantics were not enforced.
This breaks a bunch of stuff in the test suite, but luckily there is an easy fix: turn off "devtool" in the config and you …
=> Don't let webpack use "eval" devtool in tests

karma.common.js, package.json
A few changes in here:
- Split out one of the preprocessor patterns into two lines so that readers don't have to look up the significance of "+"; if you're curious, it is explained [here](https://github.com/isaacs/minimatch).
- Create `DEBUG` constant (set when running with the `-d` or `--debug` flags) for readability and use it in a few places.
- When `DEBUG` is set, increase log level from "info" to "debug".
- When `DEBUG` is set, set "singleRun" to `true`, which means you can interact with the tests in the browser console.
- Add a "test:debug" script to run with `--debug`; this is a shortcut for doing `npm run test -- --debug`.
- Produce coverage information for "src", not "test"; seems like this was back-to-front.
Doing this in service of: …
=> Add test:debug script for investigating test issues

test/lib/utils.js, test/plugins/test/embed.js
Alas, I have to reintroduce the hack that I removed in c7f77084e7a5631e4814c92bf1. Notice though that I am not applying it in a blanket fashion everywhere -- that just makes other failures pop up elsewhere -- but instead am targeting it to the two places that need it. There are only two other failing tests in Firefox visible with `npm run test:debug` right now. If they require a similar fix I'll extract out the hack.
This is some really baffling behavior. To summarize:
- Tests only fail on Firefox, and only if a test has run before.
- In fact, it is not even necessary to run a test before to trigger the failure: just adding a "div" with a "contenteditable" attribute to the DOM is enough (removing it makes no difference).
- As I was single-stepping through the debugger, I saw CKEDITOR …
=> Fix embed tests

test/ui/test/button-embed-edit.jsx
With this we now have a 100% clean `npm run test:debug` run (in browser, in Firefox); that's around 350 tests.
=> Fix button-embed-edit tests

karma.common.js
While working on #1148 some of the tests would end up throwing exceptions deep inside the minified CKEDITOR source. You can get the debugger to "pretty print", but it's still super hard to find your way around because all the variable names are minified.
Test plan: `npm run test` (all pass), `npm run test:debug` (see all pass except for two pre-existing failures, and see via the browser dev tools that the CKEDITOR source is unminified).
Builds on: https://github.com/liferay/alloy-editor/pull/1155
Closes: https://github.com/liferay/alloy-editor/issues/1150
=> Make it possible to run with non-minified CKEDITOR build

test/index.js, test/lib/mocha.js, test/plugins/test/embed.js, test/ui/test/alloy-editor.js, test/ui/test/button-embed-edit.jsx
Sinon has a "sandbox" feature that allows you to create stubs anywhere and then clean them up with a single call to `sandbox.restore()`. I just learned that as of v5, the `sinon` object is itself a sandbox, which means that we can:
1. Remove the places where we manually set up a new sandbox and just call `sinon.stub()` etc directly.
2. Add a `sinon.restore()` call in a global "afterHook" and be sure that clean-up is never forgotten.
3. Remove existing scattered calls to `restore()`.
See:
https://sinonjs.org/releases/latest/sandbox/
Test plan: `npm run build && npm run test:debug` and see all tests pass.
=> Streamline and fool-proof-ize the clean up of Sinon stubs

package-lock.json, package.json
As well as adding "^" to the version range, which should be totally safe with React because they follow semver very rigorously.
Test plan: sanity check by running `npm run build && npm run test:debug`
=> Update to react/react-dom 16.8.3

src/components/base/widget-position.js
https://github.com/liferay/alloy-editor/issues/1160
https://issues.liferay.com/browse/LPS-91194
I included `pointerEvents: 'none'` to the style to prevent any unwanted button selections. Then applied a `transitionend` event listener. Only when the transition has completed will the pointerEvents be removed and allow the user to interact with the toolbar.
Thank you.
=> Fixes #1160 Add transitionend event to enable pointerEvents

.gitignore
So that you can run `git worktree add website origin/website` (or similar) and have a handy checkout of the website branch in a way that doesn't interfere with work on the master branch.
=> Make it convenient to check out website as worktree

package.json
Over in this comment I did a bit of a mini-audit of how we're using script names in a number of projects, and noticed that we have some redundant tasks in this project:
https://github.com/liferay/liferay-npm-tools/pull/41#discussion_r269474322
Specifically, we have "checkFormat" and "prettier", which both duplicate "format".
Closes: https://github.com/liferay/alloy-editor/issues/1187
=> chore: Clean up redundant script names (#1187)

content/docs/develop/how-to-build-it.md
Note that we have to keep the old 1.x instructions around as well, because we continue to make bug-fix releases on that branch.
Closes: https://github.com/liferay/alloy-editor/issues/1197
=> doc: Update build instructions for v2.x (#1197)

content/docs/develop/create_skin.md
`yarn build` was dying with:
```
error Plugin gatsby-mdx returned an error
SyntaxError: unknown: Expected corresponding JSX closing tag for <MDXTag> (4:0)
```
Closes: https://github.com/liferay/alloy-editor/issues/1204
=> fix: broken website builds due to malformed Markdown (#1204)

README.md, package.json, yarn.lock
And remove now-unused `gh-pages` package.
This shows the steps we took to publish an update to the website just now. This will change soon because we'll have to move off of WeDeploy, but may as well keep the README.md current in the meantime.
=> doc: document deployment process

package.json, yarn.lock
We're using clay-css for the spritesheet, but we had it pinned to an old version. In liferay-portal, we're using clay-css 2.11.1 right now, and there's no reason why we shouldn't just use the same here. So I'm specifying a looser range. Note that the latest is actually 2.12.0, but I only ask for "^2.11.1" because I want `yarn` in the portal to resolve clay-css to a single version.
Test plan: `yarn dev && yarn start`
Closes: https://github.com/liferay/alloy-editor/issues/1220
=> chore: Update to latest clay-css (#1220)

gatsby-browser.js, package.json, yarn.lock
This is the follow-up to #1230, and makes the demo fully functional in IE11 (well, as fully functional as IE ever is).
Test plan: `yarn build && yarn serve`, then hit demo from VirtualBox VM (http://localhost:9000).
Closes: https://github.com/liferay/alloy-editor/issues/1227
=> fix: add svg4everybody polyfill to make demo work on IE11 (#1227)

deploy.sh
Two enhancements here:
- Infer the remote name (which could be any of "origin", "upstream" etc).
- Update "gh-pages" before producing a new commit on top.
=> feat: improve handling of gh-pages in deploy.sh

webpack.common.js
It turns out that the "test" property in the Webpack build needs to be in a different format on Windows, otherwise it never matches, which means that our file at "scripts/build/version.js" doesn't pass through the val-loader, and in turn means that we produce untransformed output that IE 11 will choke on (an arrow function, and even if we fixed it, it would probably choke on the backticks).
You can make the build work on Windows by passing `path.resolve('scripts/build/version.js')` instead; this produces an absolute path with the appropriate Windows-style backslashes. But then the build doesn't work on macOS. If you try to make it a relative path (`path.relative('', path.resolve(...))`) then Webpack rejects it.
So, the solution is to make a RegExp with the backslashes (if present) …
=> fix: console errors in Windows-based build (#1228)

.travis.yml
Because node-sass is not compatible with the just-released v12, and is causing all CI runs to blow up; example:
https://travis-ci.org/liferay/alloy-editor/builds/523839150
Closes: https://github.com/liferay/alloy-editor/issues/1237
=> chore: make Travis use Node v11 (#1237)

content/docs/use/how_to_use_it.md, content/docs/use/use.md, gatsby-config.js, package.json, src/pages/index.js, yarn.lock
- Drops misleading reference to "IE9+"; we officially support "IE11" as described in #1161.
- Get rid of odious "article1", "article2" etc ids because I need to link to a specific section in "how_to_use_it.md"; we should do this everywhere but it is beyond the scope of this commit.
- Describe needed polyfills on "how_to_use_it.md".
- Provide a link to the polyfills section on "how_to_use_it.md" from "use.md".
- Add gatsby-plugin-catch-links plugin so that the aforementioned link doesn't force an unnecessary full page-reload.
Test plan: `yarn start` and check out the edited pages. Also, use the network pane to confirm that the full page-reload isn't happening.
Closes: https://github.com/liferay/alloy-editor/issues/1243
=> feat: improve documentation on level of IE support (#1243)

webpack.common.js
…ackslashes into the proper regular expression format that they need to be in
Sent in to fix https://github.com/liferay/alloy-editor/issues/1251 in relation to https://github.com/liferay/alloy-editor/pull/1236
=> fix: backslash escaping on Windows builds (#1251)

src/components/buttons/button-color.jsx
Fixes:
src/components/buttons/button-color.jsx
88:7  error  'activeColorClass' is assigned a value but never used  no-unused-vars
which became unused in 12e5c779b.
=> chore: fix lint

src/plugins/dragresize_ie11.js
Make the drag handler opaque, change the color to white to make it stand out more and move the handle so it is more visibly separate from the image
Fixes https://github.com/liferay/alloy-editor/issues/1255
I decided to add the styles inline as CKEditor by default already adds the styles in-line and this seemed like a cleaner implementation within the CKEditor framework than trying to implement it using real CSS.
=> fix: improve drag handler visibility on IE (#1255)

package.json, scripts/publish/check.js
I extended the scripts/publish/check.js script to make sure we don't push a release without having an annotated tag for it.
Seeing as the script now does more than just check the dist files, I renamed the corresponding package.json script from "check:dist" to "check:version".
Closes: https://github.com/liferay/alloy-editor/issues/1263
=> feat: add check to prevent publishing without annotated tag

src/plugins/dragresize_ie11.js
…e styling
https://github.com/liferay/alloy-editor/issues/1275
Instead of removing all the styles, keep the width (controls sizing) style
=> fix(ie): make IE preserve other browsers' image width styling (#1275)

src/plugins/dragresize_ie11.js, src/ui/react/test/selection-test.js
1.x cherry-pick of 2.x fix: https://github.com/liferay/alloy-editor/pull/1276
=> fix: make IE preserve other browsers' image width styling

src/plugins/dragresize_ie11.js
Fixes #1289
https://issues.liferay.com/browse/LPS-98250
`imageStyles` needs to be checked before getting any information from it.
Thank you.
=> fix(ie): add a check for 'imageStyles' before accessing (#1289)

package.json, src/ui/react/karma-saucelabs.js, test/core/karma.js, test/plugins/karma.js, yarn.lock
To see whether that fixes the CI failures which report:
Your Sauce Connect version (4.4.0) is no longer supported
like seen on [this PR](https://github.com/liferay/alloy-editor/pull/1284).
=> fix: broken CI on 1.x branch

src/components/buttons/button-remove-image.jsx
Closes: https://github.com/liferay/alloy-editor/issues/1286
Test plan: `yarn build`, `yarn start`, see tooltip on remove-image button when hovering over an image toolbar.
=> fix: missing tooltip on remove-image button (#1286)

src/adapter/core.js, src/components/buttons/button-image.jsx
In 8a0aaf75ee8c223a776f4b0f08d3953 we added a button (button-item-selector-image.jsx) with a duplicate "image" key, clobbering the existing "image" button (in button-image.jsx). Because of the way object literals work in JS, when we list the buttons in "src/components/buttons/index.js", the old image button is mapped to "image", then the new button is mapped over the top, overwriting it.
The new button works in Liferay DXP because we have the necessary "imageselector" command, but in the demo, it does nothing.
Fix is to pick a non-colliding name ("imageFromFile"). That fixes the demo, and it doesn't break DXP because DXP doesn't actually use the src/adapter/core.js to define what goes in each toolbar, instead using the system described here: …
=> fix: make demo insert-image button work again (#1291)

src/plugins/dragresize_ie11.js
Fixes https://github.com/liferay/alloy-editor/issues/1297
Saving the image in IE sets/overrides the height value, so style height also needs to be preserved.
=> fix: make IE also preserve other browers' image height styling

src/plugins/dragresize_ie11.js
This is to fix the issues described https://github.com/liferay/alloy-editor/pull/1298#discussion_r310046875.  We're guarding against null values for height and width styles
=> fix: check whether height and width style exist before using

package.json
We had no business bundling this with the non-dev dependencies. It is only used by Karma and webpack.
=> fix: move val-loader out of dependencies into devDependencies

.eslintrc.js, src/adapter/main.js, src/components/base/index.js, src/components/compat/button-action-style.js, src/components/compat/button-command-active.js, src/components/compat/button-command.js, src/components/compat/button-keystroke.js, src/components/compat/button-props.js, src/components/compat/button-state-classes.js, src/components/compat/button-style.js, src/components/compat/index.js, src/components/compat/toolbar-buttons.js, src/components/compat/widget-arrow-box.js, src/components/compat/widget-dropdown.js, src/components/compat/widget-exclusive.js, src/components/compat/widget-focus-manager.js, src/components/compat/widget-interaction-point.js, src/components/compat/widget-position.js
Please see the commit messages for details. The first one contains the juicy bit:
> Exposes:
>
> - The 2.x HOCs as `AlloyEditor.Base.ButtonCommand` (etc) so that people can write custom buttons using the new ES6-class based style.
> - The 1.x mixins as `AlloyEditor.Compat.ButtonCommand` (etc), for people who have custom buttons written using the old (`React.createClass`) style.
>
> The obvious downside here is that we're shipping more code now, increasing the bundle size and overall complexity, but we think it's worth it because we are prepared to pay quite a high cost in the name of maintaining backwards compatibility.
>
> Having said that, we are not going to go out of our way to document the `Compat` mixins at this time, so as not to overwhelm users; this is just something we want to …
=> feat: make it possible to build custom buttons that use "mixins"

src/components/buttons/button-spacing.jsx
Hey @wincent, @julien, just saw this in reference to https://issues.liferay.com/browse/LPS-102718 which is actually throwing an error there... it might be a different thing though, but this at least looked off...
Also, I assume there's something wrong in the description here, as it states:
```
* The ButtonSpacing class provides functionality for changing text color in a document.
```
We might need to update that :D
=> fix(button-spacing): adds missing EditorContext ref

.gitignore, public/CNAME
If you look at [the commits on the gh-pages branch to the "CNAME" file](https://github.com/liferay/alloy-editor/commits/0bc43b350037a12132f7178c292ec90a964f40f3/CNAME
) you'll see that it was getting blown away on every site build and we've had to manually restore it each time.
This commit includes it in the "public" directory, which is used by the deploy.sh script as a basis for creating commits on the gh-pages branch, so that the file will stick around on every build.
Test plan: run `deploy.sh` (no need to actually `git push` the result) and inspect the generated commit; see that it did not delete the CNAME file from the `gh-pages` branch.
=> fix: include CNAME in public directory

.gitignore
Makes it convenient to have "1.x" and "gh-pages" checkouts nested in a repo clone (eg. created with `git worktree add gh-pages gh-pages` etc).
=> feat: add some useful worktree-related .gitignore entries

README.md
We already purged references to IE9 from the website in:
https://github.com/liferay/alloy-editor/pull/1244
But as pointed out in the related issue, the README still has a lingering reference to IE9.
IE11 is our baseline for support, as noted here:
https://github.com/liferay/alloy-editor/issues/1161
Any currently-tracked IE-related bugs and issues should appear under the "browser: ie" label:
https://github.com/liferay/alloy-editor/issues?q=is%3Aissue+is%3Aopen+label%3A%22browser%3A+ie%22
Closes: https://github.com/liferay/alloy-editor/issues/1357
=> docs: remove reference to IE9+ from README (#1357)

src/components/buttons/button-accessibility-image-alt.jsx
Added in: https://github.com/liferay/alloy-editor/pull/1377
We don't need the `imageElement &&` here; we just checked `imageElement` on the line above.
=> refactor: avoid useless boolean expression

src/plugins/autolink.js, test/plugins/test/autolink.js
see https://issues.liferay.com/browse/LPS-99704
=> fix: make REGEX_URL validate links and stop validating non links

CHANGELOG.md
I just want to make sure that these two pulls to the generator are good before publishing a new release:
- https://github.com/liferay/liferay-npm-tools/pull/398
- https://github.com/liferay/liferay-npm-tools/pull/399
So this is just a test of those, done with:
../liferay-npm-tools/packages/liferay-changelog-generator/bin/liferay-changelog-generator.js \
--from=v1.5.19 \
--to=v2.11.5 \
--regenerate \
--version=v2.11.5
Note that I only regenerated the v2+ section of the changelog, to minimize the chaos.
=> docs: update CHANGELOG.md with new version of liferay-changelog-generator

src/components/buttons/button-accessibility-image-alt.jsx
Sometimes when interacting images in the editor,
the "selected element" can be null, and if this is the
case this code will fail.
An interesting this to note is that this code runs
although we haven't interacted with this
'button-accessibility-image-alt.jsx' component (probably
due to the fact these components are all HOCs)
=> fix: check that the selected element is valid

src/plugins/embedurl.js
Is fixing #1393 If data-style attribute is not a valid JSON an exception will be thrown and the code will stop working.
=> fix: gracefully handle invalid JSON in data-style attribute (#1393)

src/plugins/tabletools.js
After the user adds a new row into the table, it is added, but the old row/cell is focused. And the toolbar is shown for the old one.
This change fixes it: after the new row is added to the table, it is selected and its toolbar is shown.
=> fix: select new cell after the new row/column is inserted

src/selections/selection-position.js
This change, makes the toolbar always visible when editing tables,
The toolbar will move above the current row or column currently being
edited.
Closes #1403
=> feat: make the toolbar visible in tables

scripts/build/build-ckeditor.sh
Noticed that this had drifted out of sync since the last time we did a build:
- Built files are now stored under lib/.
- We use Conventional Commits format for our commit messages now.
Originally part of: https://github.com/liferay/alloy-editor/pull/1396
But that got superseded by: https://github.com/liferay/alloy-editor/pull/1402
So I salvaged this commit and am sending it separately.
=> fix: update instructions at end of build script

src/selections/selection-position.js
Noticed while testing https://github.com/liferay/alloy-editor/pull/1414 a bunch of console spew coming from the `getClientRect()` calls in selection-position.js. These prevent the toolbar from being shown. I gather I am not the only one who sees this, because in @diegonvs's screencap gif on #1414 you can also see there is no toolbar.
This looks like a regression introduced in bef3ce28. I don't know why we didn't catch it during initial testing; that made me think that it might actually be the subsequent CKEditor update that exposed the problem, but no, when I go back to bef3ce28 I can repro the error. You can see in @julien's [original PR](https://github.com/liferay/alloy-editor/pull/1404) a screencap gif of it working for him.
The problem is that `startContainer` may be a text node, …
=> fix: avoid JS error computing selection position

src/components/buttons/button-table-edit.jsx
When inserting data, everything must be wrapped up on the cell and cell width couldn't expand.
It is impossible to use the drag ability to resize a column when other columns in the table have content which then pushes the empty columns together.
Based on https://github.com/ckeditor/ckeditor4/issues/3614#issuecomment-549410457 I just changed the table style directly on the table definition. 
Fixes: https://issues.liferay.com/browse/LPS-114429
=> fix: unbreak table drag-resizing by using fixed table layout

src/plugins/dragresize.js
From original issue:
**Do you want to request a _feature_ or report a _bug_?**
bug
**What is the current behavior?**
* resizing an image in IE11 sets the style, height, and width attributes
* resizing an image in Chrome or Firefox sets only the style attribute
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
1. Open Chrome, resize the image in the demo site `fullmoon.thumbnail.jpg` and inspect the element, noticing there are no width and height attributes
2. Open Firefox, resize the image in the demo site `fullmoon.thumbnail.jpg` and inspect the element, noticing there are no width and height attributes
3. Open Firefox, resize the image in the demo site `fullmoon.thumbnail.jpg` and inspect the element, noticing …
=> fix: set width and height attributes for firefox and chrome (#1412)

src/components/buttons/button-table-edit.jsx, test/ui/test/button-table-edit.jsx, test/ui/test/fixtures/1_by_1_table.html
…`col` value when creating a table
Run Demo Page:
Click on AE's plus Icon, add a Table with 0 for number of columns and -1 for number of rows
Currently AE allows the user for input negative values for cols/rows.
I restricted the user to set a value less than the minimum value for col/row defined on html element just preventing the user to type negative values from the keyboard. That was already defined to `-1`. See https://github.com/liferay/alloy-editor/compare/master...diegonvs:110423?expand=1&title=fix%3A+Don%27t+allow+users+to+input+a+value+less+than+a+minimum+%60row%60+or+%60col%60+value+when+creating+a+table#diff-4b5fe36c64a18eb8591a90632c092ee0L164
@drakonux, from a UX perspective, is it correct? An alternative can be providing a validation message.
Closes: …
=> fix: Don't allow users to input a value less than a minimum `row` or `col` value when creating a table

src/components/buttons/button-table-edit.jsx
1. Open "Advanced Editing Demo" from the current master
2. Click on the add button for adding a grid
3. Try to type the number `22` cleaning the current value and just typing `22`
It's not possible settling this number because the onChange event is being triggered for every keyboard input like `delete`.
I tried to fix it changing from `onChange` to `onInput` but I didn't get success, also, I tried to use `onBlur` for just updating the input when the input is blurred but no success. The only alternative that I've found was when submitting the value from the inputs, validate, and then just changing the minimum value if received an invalid value.
After the mentioned changes:
=> fix: Avoids blocking user input when settling a minimal input value

src/components/base/toolbar-buttons.js
Hey,
Github issue: https://github.com/liferay/alloy-editor/issues/1424
[LPS-120361](https://issues.liferay.com/browse/LPS-120361)
Note in order to test in liferay [LPS-120360](https://issues.liferay.com/browse/LPS-120360) has to be applied
Also there is a discussion at [PTR-1918](https://issues.liferay.com/browse/PTR-1918) about why we decided we should fix this in AE.
Please review my change,
Thanks
=> fix: correct toolbar misalignment when editor is rendered in modal and the uiNode is provided

.yarnrc
So that we can create prerelease test releases like we do in liferay-js-themes-toolkit with `yarn version --prepatch` and so on:
- https://classic.yarnpkg.com/en/docs/cli/version/
- https://github.com/liferay/liferay-js-themes-toolkit/blob/cefa75c9c64/.yarnrc (ie. current master)
I used this to produce
- https://github.com/liferay/alloy-editor/releases/tag/v2.11.14-pre.0
And documented the process here:
- https://github.com/liferay/alloy-editor/wiki/Contributing/_compare/7f5484e35a...28f26cca11
=> chore: config Yarn to use "pre" as preid

src/plugins/dragresize_ie11.js
From original issue:
**Do you want to request a _feature_ or report a _bug_?**
bug
**What is the current behavior?**
* resizing an image in IE11 sets the height attribute to an explicit pixel value even if dimensions are locked
* resizing an image in Chrome or Firefox does not set a height attribute and sets the height style to `auto`
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
1. Open Chrome, resize the image in the demo site `fullmoon.thumbnail.jpg` and inspect the element, noticing there is no height attribute, and the style is `height: auto`
2. Open Firefox, resize the image in the demo site `fullmoon.thumbnail.jpg` and inspect the element, noticing there is no height attribute, and the style is `height: …
=> fix: if we're locking the image attributes, use 'auto' for the height like we do in other browsers

src/components/buttons/button-link-edit.jsx
**Forwarded from [https://github.com/julien/alloy-editor/pull/10](https://github.com/julien/alloy-editor/pull/10)**
Original pull request message:
Hi @julien ,
These are the changes I believe we need to make to achieve what's been discussed in https://issues.liferay.com/browse/PTR-2196: keep the focus on the current element when we are editing a link. The toolbar will also remain open since the focus is still on a linked element (unless we remove the link).
There is also an open LPS to manage these change (increment alloyeditor version) within liferay-portal you can use:
https://issues.liferay.com/browse/LPS-126034
Please let us know if the modifications look good to you or if anything else is needed.
Thank you!
//cc @antonio-ortega @mariapicadoal
---
Test plan:
- Run `yarn start`
- Visit …
=> fix: Do not advance selection when editing a link

src/selections/selection-position.js
Hey guys,
Can you have review this pull request, please?
It is just one more time the case when we need to consider the scroll from top of the uiNode we are passing to the editor.
Closes: https://github.com/liferay/alloy-editor/issues/1466
Thanks.
Regards.
/cc @crodriguezy
=> fix: Toolbar is not correctly positioned when editing tables and images within a modal window

src/adapter/core.js
=> fix: use `ALLOYEDITOR_BASEPATH` in spritemap default value

src/components/buttons/button-paragraph-align.jsx
Fixes: #1500
If you add 'paragraphAlign' button to Alloy Editor Configurator and you add a paragraph text with an image inside, it will fail to open the menu. Check https://issues.liferay.com/browse/LPS-138431
=>  fix: Prevent activeCommand in button-paragraph-align.jsx to be undefined (#1500)

src/core/link.js
Hello,
fix: automatically add 'rel' attribute to the generated links to prevent tabnabbing security vulnerability
issue: https://github.com/liferay/alloy-editor/issues/1521
I have added "noreferrer" value as well since "noopener" is not compatible with IE11 and earlier Liferay versions (<7.4) support IE11 browser as well.
Related tickets:
- https://issues.liferay.com/browse/LPS-151771
- https://issues.liferay.com/browse/PTR-3001
Could you please review it? 
cc. @antonio-ortega 
Thanks.
=> fix: add 'rel' attribute to the generated links

src/components/buttons/button-indent-block.jsx, src/components/buttons/button-outdent-block.jsx
https://github.com/liferay/alloy-editor/issues/1524
https://issues.liferay.com/browse/LPS-152668
The indent and outdent icons are switched.
Thank you.
=> fix: #1524 indent and outdent icons are switched

src/assets/sass/components/ae-toolbar/skin.scss, src/assets/sass/components/ae-toolbar/structure.scss, src/assets/sass/skin/atlas/variables/structure.scss
Hi @liferay-frontend Team,
When clicking on the plus icon of the repeatable HTML field, the layout is shifted on the first click and the new field is not added. I think this is caused by the border style of the toolbar add button. I removed the transparent border and modified the toolbar border width a bit, so the style of the toolbar button has remained the same.
https://github.com/liferay/alloy-editor/issues/1529
LPS: https://issues.liferay.com/browse/LPS-155757
**issue**:
style of the add button before the change:
**fix**:
after:
Could you please review it?
Thank you.
=> fix: modify the toolbar add button border to outline to avoid layout shift

src/core/link.js, test/core/test/link.js, test/plugins/test/autolink.js
fixes https://github.com/liferay/alloy-editor/issues/1534
followup on https://github.com/liferay/alloy-editor/pull/1535
@bettysteger This is what I had in mind with 'squash and split code into two commits', in https://github.com/liferay/alloy-editor/pull/1535#pullrequestreview-1034129536. I don't want to waste any more of your time, so I molded commits and pushed to this PR. I still set you as the author on commits, credit where it's due :slightly_smiling_face:
=> use defaultLinkTarget when creating a link, fixes autolink

src/adapter/core.js
Related ticket: https://issues.liferay.com/browse/LPS-166754
The root cause is when switch too fast between the cards the editor DOM objects are not loaded, so it could be null on [core.js](https://github.com/liferay/alloy-editor/blob/master/src/adapter/core.js#L177,%20L180)
then the editor is failed to destroy while all the listeners are removed. When the destroy() method is invoked again it gets null when accessing the length of event handlers [EditableRichTextFragmentProcessor.es.js](https://github.com/liferay/liferay-portal-ee/blob/7.2.x/modules/apps/layout/layout-content-%20page-editor-web/src/main/resources/META-INF/resources/js/components/fragment_processors/EditableRichTextFragmentProcessor.es.js#L38,L45)
=> fix: avoid null on init and destroy the editor too fast makes the DOM is not loaded
