- src/ui/react/src/selections/selection-position.js
- src/ui/react/src/selections/selections.js
- src/ui/react/test/selection-position.jsx
Hey @ipeychev,
This sets a fixed `setPosition` function to image selection as well for #181.
I added tests for this module the best way I could imagine. Please take a look to see if you think they can be improved.
> Use centering setPositionFn for image selection by default

- src/plugins/autolink.js
Not sure how you feel about the naming or the exact code, but I'd love to have something like this.
> Allow listening for automatically-created links.

- src/core/link.js
- src/ui/react/src/components/buttons/button-link-edit.jsx
- src/ui/react/src/selections/selection-test.js
- src/ui/react/test/selection-test.js
- test/core/test/link.js
Hey @ipeychev, this could be a fix for #128 
I'm going out now, so I'm just sending this to get your opinion. I'll add tests and complete the PR tomorrow from the office :wink:
> Advance cursor after link on link changes

- src/ui/react/src/components/buttons/button-link-edit.jsx
- src/ui/react/src/components/buttons/button-link-target-edit.jsx
Hey @ipeychev, this is a possible fix for #434 
Getting closer to 1.0! :dancer:
> Allow configuring the default link target value

- src/plugins/autolink.js
See https://github.com/ckeditor/ckeditor-dev/blob/master/plugins/autolink/plugin.js for example
> [TS] LPS-84123

- package-lock.json
- package.json
Last usage was removed in 5e0cbf212f5265b9f7641fbecda0e6930e2a3775.
> Remove unused dir-compare dependency

- src/components/buttons/button-camera-image.jsx
Updated to the new refs API. Note that our direct DOM manipulation in this class isn't strictly kosher: it's ok for interacting with canvas and video elements (eg. calling `videoEl.play()`, drawing into the canvas etc) and also for focusing the button element on mount.
But there are other places where we are abusing for sure, like setting `disabled` on the button (should be component state). Having said that, in this commit I just want to make the minimal changes to fix the lints.
```
40:3   error  Do not use findDOMNode                                 react/no-find-dom-node
40:24  error  Using this.refs is deprecated                          react/no-string-refs
90:12  error  Using string literals in ref attributes is deprecated  react/no-string-refs
94:6   error  Using string literals …
```
> Fix 15 lints in src/components/buttons/button-camera-image.jsx

- src/components/buttons/button-link-edit-browse.jsx
> Fix reference error

- package-lock.json
- package.json
Test plan: `npm run build && npm run test && npm run start` and check demo.
> Update to React v16.8.1

- src/components/buttons/button-item-selector-audio.jsx
- src/components/buttons/button-item-selector-image.jsx
- src/components/buttons/button-item-selector-video.jsx
> Eliminate unused imports

- CONTRIBUTING.md
I just had to test out the changelog generation and realized
that the instructions here are lacking a bit of detail.
> Update changelog generation instructions

- CHANGELOG.md
Done using ` github_changelog_generator liferay/alloy-editor -t $TOKEN`.
> Update CHANGELOG.md to reflect recent alphas

- CONTRIBUTING.md
- "master" now fulfils the role of the old "develop" branch
- "stable" now fulfils the role of the old "master" branch
> Update CONTRIBUTING.md to reflect new branch structure

- .eslintrc.js
- package-lock.json
- package.json
No major changes, but it does allow us to turn off a suppression we we no longer need ("sort-keys").
> Update to eslint-config-liferay v3.0.0

- src/ui/react/src/components/base/widget-position.js
PR to Master: https://github.com/liferay/alloy-editor/pull/1162
#1160
https://issues.liferay.com/browse/LPS-91194
Thank you!
> Fixes #1160 Add transitionend event to enable pointerEvents

- src/html.js
- src/pages/index.js
Looks like `yarn format` hasn't been run for while, so these files were causing `yarn checkFormat` to fail.
> fix: run Prettier

- package.json
Consistency with what we have on the "master" branch as well as in several other projects.
> doc: rename checkFormat task to format:check for consistency

- scripts/build/version.js
- scripts/build/with-ckeditor.js
- scripts/build/with-react.js
- webpack.common.js
> fix: Add VERSION constant to AlloyEditor

- README.md
Closes: https://github.com/liferay/alloy-editor/issues/1212
> doc: update deployment instructions in README.md (#1212)

- src/plugins/dragresize_ie11.js
> chore: fix formatting

- src/assets/sass/components/ae-container/structure.scss
Please see https://issues.liferay.com/browse/LPS-95292 for more information.
That also means I'll cut a release.
> fix: update color for label

- src/assets/lang/language.json
- src/components/buttons/button-item-selector-audio.jsx
- src/components/buttons/button-item-selector-video.jsx
Please check my fix and push it into a new release.
> fix(a11y): add aria-label and title attributes for the audio and video button (#1281)

- src/ui/react/src/components/base/widget-position.js
@rolandpakai, I took your PR (https://github.com/liferay/alloy-editor/pull/1284) which was based on https://github.com/liferay/alloy-editor/commit/8d2a3f7ef3e708aa091d54f73e77fa2bca01af11, and rebased it on top of https://github.com/liferay/alloy-editor/pull/1292 (which fixes the CI failures). Also, I am targeting it at the "1.x" branch instead of "1.x-stable" (we only merge to the stable branches right before releasing). Now let's see what the CI says about this!
> fix(firefox): broken table toolbar (#1283)

- .eslintrc.js
- package.json
I don't really like having to add more suppressions in order to turn this on, but given that we do get PRs with formatting errors, I think it's better to have weak checks than no checks.
> feat: run formatting and lint checks in CI

- .github/semantic.yml
I believe that the bot has now been activated for this repo, so we can do exactly what we did in:
https://github.com/liferay/liferay-frontend-guidelines/pull/70
Note that I'm targeting the 1.x branch with this PR; I don't actually know if the bot will run on non-master branches so consider this a test.
> feat: configure Semantic Pull Requests bot (1.x)

- src/components/buttons/button-link-edit.jsx
> fix: avoid adding target attribute when default is selected

- .gitignore
- .npmignore
- karma-saucelabs.js
- karma.common.js
- karma.js
- package.json
- yarn.lock
Seeing as nobody is looking at this, and it is producing security noise due to the dependencies, let's just remove it.
Closes: https://github.com/liferay/alloy-editor/pull/1375
> chore: remove unused coverage functionality

- src/plugins/imagealignment.js
Fix Lack of padding around images #1367
> fix: Lack of padding around images

- src/selections/selection-position.js
Please check my changes.
The fix is addig back this: https://github.com/liferay/alloy-editor/pull/1218
cc: @julien
> fix: toolbar location for images

- LICENSE.md
Stems from https://issues.liferay.com/browse/IFI-1884
> fix: add proper license since this derives from gatsby-boilerplate
